### ISSUE TITLE
Possible to only have one instead of three members?

### ISSUE THREAD

**Issue by fire** [rabbitmq/ra#169]
During testing and small deployments I was wondering if it was possible to use only one member instead of three.

I looked at the sample and was lost.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
It is possible to have a cluster with a single member but then you have to ask yourself: why use Ra or Raft at all if you don't replicate.

**Comment by fire** [comment]
I’ll post on the mailing list asking for a ra machine sample which starts up and runs in only one member.  Thanks. The idea is a demo mode vs production mode for ra library usage.

**Comment by michaelklishin** [comment]
It would be exactly as the [Quick Start](https://github.com/rabbitmq/ra#quick-start) example but with one node instead of three.

**Comment by michaelklishin** [comment]
An example executed using `rebar3 shell` in this repo:

``` erlang
ClusterName = quick_start.
%% => quick_start
ServerId = {ClusterName, ra@mercurio}.
%% => {quick_start,ra@mercurio}
ra:start().
%% => ok
{ok, ServersStarted, ServersNotStarted} = ra:start_cluster(ClusterName, {simple, fun erlang:'+'/2, 0}, [ServerId]).
%% => 2020-02-18T18:26:01.791581+03:00 notice: {quick_start,ra@mercurio}: candidate -> leader in term: 1
%% => {ok,[{quick_start,ra@mercurio}],[]}
{ok, StateMachineResult, LeaderId} = ra:process_command(hd(ServersStarted), 5).
%% => {ok,5,{quick_start,ra@mercurio}}
{ok, 12, LeaderId1} = ra:process_command(LeaderId, 7).
%% => {ok,12,{quick_start,ra@mercurio}}
```
