### ISSUE TITLE
How disable all disk activity?

### ISSUE THREAD

**Issue by loguntsov** [rabbitmq/ra#51]
I wanted use RA library only for in-memory purposes.
So how i can disable all disk activity to use memory only ?

Thank you.

**Comment by kjnilsson** [comment]
Ra has been designed to be persistent and doesn't have an in-memory option. Partly this is due to Raft relying on "stable storage" and partly it became difficult to provide an abstraction over the storage backend that could accommodate both as well as being efficient and asynchronous.

For a consensus protocol that is designed to run in-memory look at [View Stamped Replication](http://pmg.csail.mit.edu/papers/vr-revisited.pdf)
